### ISSUE TITLE
Does not produce a error if config file is not found

### ISSUE THREAD

**Issue by andrewsav-bt** [samhocevar/rinetd#15]
The program does not produce any output if the config file is absent / not found. Is this supposed to happen?

UPDATE: hm... I can't see _any_ error for example when a host name in the config file cannot be resolved, it's as if stderr does not exist at all... I wonder what I'm doing wrong...

**Comment by andrewsav-datacom** [comment]
Okay, I looked at the source code and 

1) It appears that if file cannot be found the program just do `exit(1)` without attempting to give a message. I suggest an improvement here to show a error.

2) Program routinely logs to syslog. In particular parsing errors go to syslog. If I'm running in a docker container I do not have the syslog. So another suggested improvement is to have an option to log to stderr/stdout instead of syslog.

Thank you.

**Comment by samhocevar** [comment]
Thanks for the suggestions and sorry for acting so late on them. `rinetd` now only logs to syslog when forked to the background, otherwise it will use stderr.
